### PR TITLE
ci: use best practice

### PR DESCRIPTION
**Pull request by blaggacao**

### CODE REVIEW

**Comment by blaggacao** [comment]
@rmehta Could you please adapt the branch protection rules to check for the updated ci actions? `Server` is old and test have been broken anyway for months. I fixed them here.

**Comment by rmehta** [comment]
Updated your role to "maintain"

**Comment by blaggacao** [comment]
@rmehta Thanks, unfortunately, that doesn't seem to be "enough" for this configuration. I don't want to escalate my privileges too much, so I'd be very happy if someone from staff could have a quick look:

- Context: ecommerce_integration
- Problem: Old branch protection on "Sever" event; now "Python Unit Tests (1)"
- Ask: Update Branch Protection Rules to the new event
- Probably direct link (no access, construed): https://github.com/divnix/std/settings/branches then click on the rule and update the event

**Comment by rmehta** [comment]
updated. check? also updated you to "admin"

**Pull request merged**
