### PR TITLE
refactor: sync orders from multiple amazon account

### PR DESCRIPTION
**Pull request by s-aga-r**
Multiple documents can be added with "is_active" and "enable_sync" checked to sync orders from multiple amazon accounts every hour via hook. To sync orders from a single account, click the "Sync Orders" button.

### CODE REVIEW

**Comment by ankush** [comment]
@s-aga-r should be possible to write a patch to make this a non-breaking change. 

Whatever current settings are can be copied over as a single instance of the new doctype? :sweat_smile:

**Comment by s-aga-r** [comment]
> @s-aga-r should be possible to write a patch to make this a non-breaking change.
> 
> Whatever current settings are can be copied over as a single instance of the new doctype? 😅

I also wanted to do the same, but having a doubt. How can we get the single DocType after migration?

**Comment by ankush** [comment]
> I also wanted to do the same, but having a doubt. How can we get the single DocType after migration?

Patches run before migration for this reason only. So you can get the current document. Reload the doctype (so it will go from single to non-single) and then create a document using previously fetched single doc.

**Comment by s-aga-r** [comment]
> > I also wanted to do the same, but having a doubt. How can we get the single DocType after migration?
> 
> Patches run before migration for this reason only. So you can get the current document. Reload the doctype (so it will go from single to non-single) and then create a document using previously fetched single doc.

Thanks @ankush 😄

**Review by ankush — APPROVED** [review]

**Pull request merged**
